<?php 
// enable CORS 
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH');
header("Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With "); 
header('Content-Type: application/json');

$data = [ 
  "short" => "new json content" , 
  "regular" => "this is the new content which has been loaded with ajax" ,
  "long" => "this is the content result of the ajax request you have make for this page /json.php it was dynamically generated by php "
];

echo json_encode($data);